# # Javascript Node CircleCI 2.0 configuration file
# #
# # Check https://circleci.com/docs/2.0/language-javascript/ for more details
# #
# version: 2
# jobs:
#   build:
#     docker:
#       # specify the version you desire here
#       - image: nguyensonghao/node_selenium2

#     working_directory: ~/repo

#     steps:
#       - checkout

#       # Download and cache dependencies
#       # - restore_cache:
#       #     keys:
#       #       - v1-dependencies-{{ checksum "package.json" }}
#       #       # fallback to using the latest cache if no exact match is found
#       #       - v1-dependencies-
#       - run: npm install
#       - run: npm uninstall -g chromedriver
#       - run: npm install -g chromedriver

#       - save_cache:
#           paths:
#             - node_modules
#           key: v1-dependencies-{{ checksum "package.json" }}

#       # run tests!
#       - run: npm test

version: 2
jobs:
  build:
    docker:
      - image: circleci/node:jessie-browsers
    steps:
      - checkout
      - run:
          name: Download Selenium
          command: curl -O http://selenium-release.storage.googleapis.com/3.13/selenium-server-standalone-3.13.jar
      - run:
          name: Install Nodemodules
          command: npm install
      - run:
          name: Run Test
          command: npm test